var AWS = require('aws-sdk'),
    documentClient = new AWS.DynamoDB.DocumentClient();

exports.handler = (event, context, callback) => {

    var tableName = "member_data";
    var update_attr = `
        set md_fname = :firstName,
        md_lname = :lastName,
        md_phone = :phone,
        md_email = :email,
        md_address = :address,
        md_apt = :apt,
        md_city = :city,
        md_state = :state,
        md_zip_code = :zip,
        md_emrg_name = :emrgName,
        md_emrg_relation = :emrgRelation,
        md_emrg_phone = :emrgPhone,
        md_emrg_email = :emrgEmail,
        md_dob = :dob,
        md_is_spouse = :isSpouse,
        md_is_disabled = :isDisabled,
        md_AYDALWS = :AYDALWS,
        md_is_veteran =:isVeteran,
        md_race = :race,
        md_ethnicity = :ethnicity,
        md_gender = :gender,
        md_NIH = :numInHousehold,
        md_IOPC =:isOnePersonCaregiver,
        md_monthly_household_income = :monthlyHouseholdIncome,
        md_AYRSUNFCSP = :AYRSUNFCSP, 
        md_caregiver = :caregiver,
        md_DYRASA = :DYRASA,
        md_is_services_required = :servicesRequired,
        md_notes = :notes,
        md_WTMBUMOW = :WTMBUMOW,
        md_HTUMB = :HTUMB,
        md_start_date = :startDate,
        md_del_length = :deliveryLength,
        md_del_type = :deliveryType,
        md_del_days = :deliveryDays,
        md_microwave = :microwave,
        md_is_allergies = :isAllergies,
        md_please_specify = :pleaseSpecify,
        md_meal_type = :mealType,
        md_milk_type = :milkType,
        md_AMI = :AMI,
        md_driverInstr = :driverInstr,
        md_additComm = :additComm,
        md_PDON = :PDON,
        md_PDN = :PDN,
        md_DPN = :DPN,
        md_DE = :DE`;

    var params = {
        TableName: tableName,
        Key: {
            "id": event.id
        },
        UpdateExpression: update_attr,
        ExpressionAttributeValues:
        {
            ":firstName": event.firstName,
            ":lastName": event.lastName,
            ":phone": event.phone,
            ":email": event.email,
            ":address": event.address,
            ":apt": event.apt,
            ":city": event.city,
            ":state": event.state,
            ":zip": event.zip,
            ":emrgName": event.emrgName,
            ":emrgRelation": event.emrgRelation,
            ":emrgPhone": event.emrgPhone,
            ":emrgEmail": event.emrgEmail,
            ":dob": event.dob,
            ":isSpouse": event.isSpouse,
            ":isDisabled": event.isDisabled,
            ":AYDALWS": event.AYDALWS,
            ":isVeteran": event.isVeteran,
            ":race": event.race,
            ":ethnicity": event.ethnicity,
            ":gender": event.gender,
            ":numInHousehold": event.numInHousehold,
            ":isOnePersonCaregiver": event.isOnePersonCaregiver,
            ":monthlyHouseholdIncome": event.monthlyHouseholdIncome,
            ":AYRSUNFCSP": event.AYRSUNFCSP,
            ":caregiver": event.caregiver,
            ":DYRASA": event.DYRASA,
            ":servicesRequired": event.servicesRequired,
            ":notes": event.notes,
            ":WTMBUMOW": event.WTMBUMOW,
            ":HTUMB": event.HTUMB,
            ":startDate": event.startDate,
            ":deliveryLength": event.deliveryLength,
            ":deliveryType": event.deliveryType,
            ":deliveryDays": event.deliveryDays,
            ":microwave": event.microwave,
            ":isAllergies": event.isAllergies,
            ":pleaseSpecify": event.pleaseSpecify,
            ":mealType": event.mealType,
            ":milkType": event.milkType,
            ":AMI": event.AMI,
            ":driverInstr": event.driverInstr,
            ":additComm": event.additComm,
            ":PDON": event.PDON,
            ":PDN": event.PDN,
            ":DPN": event.DPN,
            ":DE": event.DE
        }
    };

    documentClient.update(params, function (err, data) {
        callback(err, {
            "message": "member data updated successfully."
        });
    });
};

// TEST
/*
{
        "id": "2bc6d8d0-57e5-11e9-bab9-f7de274aa13b",
        "firstName": "TEST",
        "lastName": "TEST",
        "phone": "TEST",
        "email": "TEST@AOL.com",
        "address": "TEST",
        "apt": "TEST",
        "city": "TEST",
        "state": "TEST",
        "zip": "TEST",
        "emrgName": "TEST",
        "emrgRelation": "TEST",
        "emrgPhone": "TEST",
        "emrgEmail": "emrgtest@AOL.com",
        "dob": "TEST",
        "isSpouse": "TEST",
        "isDisabled": "TEST",
        "AYDALWS": "TEST",
        "isVeteran": "TEST",
        "race": "TEST",
        "ethnicity": "TEST",
        "gender": "TEST",
        "numInHousehold": "TEST",
        "isOnePersonCaregiver": "TEST",
        "monthlyHouseholdIncome": "TEST",
        "AYRSUNFCSP": "TEST",
        "caregiver": "TEST",
        "DYRASA": "TEST",
        "servicesRequired": "TEST",
        "notes": "TEST",
        "WTMBUMOW": "TEST",
        "HTUMB": "TEST",
        "startDate": "TEST",
        "deliveryLength": "TEST",
        "deliveryType": "TEST",
        "deliveryDays": "TEST",
        "microwave": "TEST",
        "isAllergies": "TEST",
        "pleaseSpecify": "TEST",
        "mealType": "TEST",
        "milkType": "TEST",
        "AMI": "TEST",
        "driverInstr": "TEST",
        "additComm": "TEST",
        "PDON": "TEST",
        "PDN": "TEST",
        "DPN": "TEST",
        "DE": "TEST"
}
*/